### PR TITLE
Alter API request format to JSON 

### LINKED ISSUE #27: No data displayed!
Hello !

I have installed and configured the Matomo plugin but no information is displayed and no error is displayed to understand what it's all about.

1. I've been using Matomo for a while so the data exists
2. the URL + siteId + token information are correctly filled in
3. When I click on the Matomo link of the plugin I arrive correctly at my destination!
4. the Debug option is set to true in the configuration

- Matomo v4.0.0
- working on localhost

I don't know how to solve the problem. :-(

Capture d’écran 2020-11-25 à 19 14 53

### PR DESCRIPTION
**Pull request by ehmeister**
Fixes #27 

Hi, with the recent Matomo 4.0 update i.a. following changes were made to the HTTP API:
- The API response format php has been removed.
- The response of an individual request within the bulk request of API.getBulkRequest may change if the API returns a scalar value (eg 5). In this case the response will be no longer 5 but for example {value: 5}

I altered the API request format to JSON and made some quick adjustments in view of the change in the response of "API.getBulkRequest". 😊

### CODE REVIEW

**Comment by DominiqueVial** [comment]
Thank you for your work!

I've tried this fix and I can have data. But results is not stable at I have to refresh browser several times to obtain data. Sometimes graph does not display, sometimes it is displayed but numerical data.

**Comment by studiosirup** [comment]
Thank you @ehmeister it works! Only the widgets don't get data. Do you have an idea for them to? Thank you for your efforts.

**Comment by ehmeister** [comment]
Since everything (including the widgets) is working perfectly fine on my end for days now, I am afraid I have currently no idea why it isn't working properly for you guys.

**Comment by studiosirup** [comment]
Yes, you're right, it works all perfectly fine here too. Thanks again.

**Comment by pReya** [comment]
@sylvainjule Any chance you can get this merged?

**Comment by sylvainjule** [comment]
Apologies for the delay everyone! Many thanks @ehmeister for the fix! :)

**Pull request merged**
